[profile.default]
solc = "0.8.10"
bytecode_hash = "none"
optimizer = true
optimizer-runs = 10_000_000
via_ir = false
runs = 256
gas_reports = ["ATokenVault"]

[fuzz]
max_test_rejects = 65536
runs = 256

[profile.intense.fuzz]
runs = 10000

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
fuji = "${FUJI_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mumbai = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
fuji = { key = "${FUJI_API_KEY}" }
avalanche = { key = "${AVALANCHE_API_KEY}" }